name: pre-commit
description: run pre-commit

inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: "--all-files"

runs:
  using: composite
  steps:
    - name: Install pre-commit
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --require-hashes -r "$GITHUB_ACTION_PATH/requirements.txt"

    - name: Cache pre-commit
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}|${{ hashFiles(format('{0}/requirements.txt', github.action_path)) }}

    - name: Run pre-commit
      env:
        EXTRA_ARGS: ${{ inputs.extra_args }}
      run: pre-commit run --show-diff-on-failure --color=always $EXTRA_ARGS
      shell: bash
