name: Checks

on:
  push:
    tags:
      - "v*"
    branches:
      - main

  pull_request:
    branches:
      - "main"
      - "dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Run pre-commit hooks
        uses: hibare/.github/github/shared-workflows/pre-commit/@ec61c90a75c7438d3fa683fffffd83908d1e7447 # v0.10.0
