name: Checks

on:
  push:
    tags:
      - "v*"
    branches:
      - main

  pull_request:
    branches:
      - "main"
      - "dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0

      - name: Run pre-commit hooks
        uses: hibare/.github/github/shared-workflows/pre-commit/@dd476a05b332ac90984ccd15a52df080b0b649b3 # v0.12.0
